### ISSUE TITLE
Baremetal  auto  enlist/discover

### ISSUE THREAD

**Issue by sheepcat** [tinkerbell/boots#231] opened 2022-01-20 11:43 UTC
now we can add hardware by only one way:  collect the mac and assign ip  in  advance. 

Is there any plan to add a feature that  hardware can enlist automaticlly?

**Comment by chrisdoherty4** [comment] 2022-05-03 15:36
Dupe of #178. @jacobweinstock to close.

**Closed** 2022-05-03 15:36 UTC
Labels: triage/duplicate
